theme: jekyll-theme-minimal
title: Copy House Homepage
description: This is the copyhouse website

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

collections:
  clients:
    output: false
  insights:
    output: true
    permalink: /insights/:path/