theme: null
title: Copy House Homepage
description: This is the copyhouse website

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

sass:
  load_paths:
    - _sass
  style: compressed

collections:
  addresses:
    output: true
  services:
    output: true
  about-copyhouse:
    output: false
  case-studies:
    output: true
    permalink: /work/:path/
  insights:
    output: true
    permalink: /insights/:path/
