theme: null
title: Copy House Homepage
description: This is the copyhouse website

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate-v2

sass:
  load_paths:
    - _sass
  style: compressed

pagination:
  enabled: true
  per_page: 6
  permalink: '/marketing-insights/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  collection: insights

collections:
  addresses:
    output: true
  services:
    output: true
  about-copyhouse:
    output: false
  case-studies:
    output: true
    permalink: /work/:path/
  insights:
    output: true
    permalink: /marketing-insights/:path/
